version: "3.8"

networks:
  backend:
    name: backend
    driver: bridge

volumes:
  postgres_data:
    name: postgres_data
    driver: local

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped