spring:
  application:
    name: backend
  config:
    import: optional:file:.env[.properties]
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver