spring:
  application:
    name: backend
  config:
    import: optional:file:.env[.properties]
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

jwt:
  expiration: 3600000
  secret: ${JWT_SECRET}

gmail:
  username: ${GMAIL_USERNAME}
  password: ${GMAIL_PASSWORD}

aws:
  secret-key: ${AWS_SECRET_KEY}
  access-key: ${AWS_ACCESS_KEY}
  region: ${AWS_REGION}
  user-avatars-bucket:
    name: ${USER_AVATARS_BUCKET_NAME}