spring:
  application:
    name: backend
  config:
    import: optional:file:.env[.properties]
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      resolve-lazily: true

logging:
  level:
    org.springframework.data.elasticsearch: DEBUG
    org.elasticsearch.client: DEBUG

server:
  tomcat:
    max-swallow-size: 100MB

jwt:
  expiration: 36000000
  secret: ${JWT_SECRET}

gmail:
  username: ${GMAIL_USERNAME}
  password: ${GMAIL_PASSWORD}

aws:
  secret-key: ${AWS_SECRET_KEY}
  access-key: ${AWS_ACCESS_KEY}
  region: ${AWS_REGION}
  user-avatars-bucket:
    name: ${USER_AVATARS_BUCKET_NAME}
  category-banners:
    name: ${CATEGORY_BANNERS_BUCKER_NAME}
  category-icons:
    name: ${CATEGORY_ICONS_BUCKER_NAME}
  post-images:
    name: ${POST_IMAGES_BUCKET_NAME}

api:
  front-end:
    host: ${FRONT_END_HOST}

elasticsearch:
  host: ${ELASTIC_HOST}
  port: ${ELASTIC_PORT}
  username: ${ELASTIC_USERNAME}
  password: ${ELASTIC_PASSWORD}